### ISSUE TITLE
Are there any benchmarks to prove the advantages of making each of these changes?

### ISSUE THREAD

**Issue by cclauss** [adamchainz/flake8-comprehensions#191]
Is there any want to demonstrate the performance or memory usage improvements that would result from making each of the recommended changes?

**Comment by adamchainz** [comment]
In general they're a good idea simply because of the memory use. Quite often it's hard to estimate the maximum size of a collection so a list comprehension instead of a generator is an unknown extra amount of memory.

A few improvements have been made to the Django ORM from these, but others have been rejected: https://github.com/django/django/pulls?q=is%3Apr+flake8-comprehensions+is%3Aclosed . It's not always cut and dry but I think a good default is to err on the side of flake8-comprehensions.

If you want to do some simple benchmarks and add to the readme that would be great.
