### ISSUE TITLE
Flag map/filter as rewritable with list comprehensions

### ISSUE THREAD

**Issue by bagerard** [adamchainz/flake8-comprehensions#365]
### Python Version

3.9.0

### flake8 Version

3.9.2

### Package Version

3.6.1

### Description

Most of the time the usage of `map/filter` can be written in a better way using a list comprehension (Encouraged in [Effective Python book]( https://hacktec.gitbooks.io/effective-python/content/en/Chapter1/Item7.html)). This is something we flag from time to time in code reviews at my company and I was wondering if this could be a feature that you could consider adding to your package or if I should work on a separate plugin for that.

**Comment by adamchainz** [comment]
Unfortunately such a rewrite is always safe, and we don't want to report false positives. `map` and `filter` return lazy objects but list comprehensions immediately evaluate, so both behaviour and performance can change. Indeed `map` and `filter` will be more performant for larger collections that aren't fully iterated.

Previous rules that encouraged an *increase* in laziness were removed after a while due to the subtle change: https://github.com/adamchainz/flake8-comprehensions/blob/main/HISTORY.rst#340-2021-03-18 . I don't want to do that again.

I guess it's at least possible to rewrite `map` and `filter` as generator expressions and retain the level of laziness, but that seems a bit minor.

If you really want this I'd say try your own plugin.

**Comment by bagerard** [comment]
Alright I understand, thanks for the quick feedback
