### ISSUE TITLE
Feature request: Check for a `list` call as argument for a function that accepts any iterable

### ISSUE THREAD

**Issue by GideonBear** [adamchainz/flake8-comprehensions#463]
### Description

For example: `''.join(list(map(f, iterable)))` can be replaced by `''.join(map(f, iterable))`.

**Comment by adamchainz** [comment]
Have you seen this pattern much? And are there other functions you'd suggest detecting this for?

**Comment by GideonBear** [comment]
No, I've not seen this pattern much, but also not the other patterns. For me, this plugin (but also lots of other flake8 plugins) are just for making sure I don't accidentally do some bad practice things. But seeing the other patterns, this was something that came to mind like "this should be here", as I think it fits with the rest of the errors.
It's quite a lot like "C414: Unnecessary <list/reversed/set/sorted/tuple> call within <list/set/sorted/tuple>()." (because the `list/reversed/set/sorted/tuple` constructors all accept iterators), and if this is implemented, C414 could be merged into this error (or the other way around).
It came to mind because it's quite common to use `list(map(f, it))` to make it a list.

For other functions, I can't really think of anything besides `str.join` and like almost everything in `itertools` right now (and `list`, `reversed`, `set` etc.), but just any function that accepts an iterable. There are obviously a lot of functions that accept an iterable, so that advice doesn't help.
I would just make a list of functions. The best would be of course to dynamically determine if the function takes an iterable, but unfortunately that's not realistically possible with a flake8 plugin (AFAIK?).

Alternatively, you could just ban any `list` call, but that seems a bit too much. You could say that any function that accepts a list should also accept an iterable, but that's not true for things that handle `Sequence`s, which can be created using `list` from an iterable.

If any other functions come to mind I'll let you know, and it's probably a good idea to just make it a list, so anyone can open a PR to add a function.

**Comment by adamchainz** [comment]
Issue #156 proposes a new rule that promotes calling `str.join` with a list comp over a generator. It may be surprising using a list is faster in that case.

The suggestion in this issue is much more niche. Since there haven't been any other reports about seeing this "in the wild", I think we can ignore this pattern for now.

Yes this plugin is here to help you avoid certain performance anti-patterns, but each rule has come from seeing the patterns in real-world code. There are infinite ways to write a slow thing, we just try to guard against those that come up, that are easily detectable :)
